{% set name = "dxcam" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dxcam-{{ version }}.tar.gz
  sha256: d524da45adf70e044865e7d4e9098e655d6734951781155dda50c1292e20d8bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - opencv
    - comtypes
    - __win

test:
  imports:
    - dxcam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ra1nty/DXcam
  summary: A Python high-performance screenshot library for Windows use Desktop Duplication API
  dev_url: https://github.com/ra1nty/DXcam
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
